# Generated by Django 6.0.7 on 2026-07-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
